name: Max input test

on:
  issues:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: extract body
      id: get_body
      run: |
        body=$(curl https://loripsum.net/api/100 | tr -d '\n')
        echo "::set-output name=body::$body"
    - name: count string length
      uses: ./.github/actions/wc
      with:
        counted_string: ${{ steps.get_body.outputs.body }}
